// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PessoasInfo.Data;

#nullable disable

namespace PessoasInfo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230212182724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PessoasInfo.Models.Detalhe", b =>
                {
                    b.Property<int>("IdDetalhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDetalhe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalhe"));

                    b.Property<string>("DetalheTexto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DetalheTexto");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaIdPessoa")
                        .HasColumnType("int");

                    b.HasKey("IdDetalhe");

                    b.HasIndex("IdDetalhe");

                    b.HasIndex("PessoaIdPessoa");

                    b.ToTable("Detalhes");
                });

            modelBuilder.Entity("PessoasInfo.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPessoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Nome");

                    b.HasKey("IdPessoa");

                    b.HasIndex("IdPessoa");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("PessoasInfo.Models.Telefone", b =>
                {
                    b.Property<int>("IdTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTelefone");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTelefone"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("BIT")
                        .HasColumnName("Ativo");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaIdPessoa")
                        .HasColumnType("int");

                    b.Property<string>("TelefoneTexto")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("VARCHAR(13)")
                        .HasColumnName("TelefoneTexto");

                    b.HasKey("IdTelefone");

                    b.HasIndex("IdTelefone");

                    b.HasIndex("PessoaIdPessoa");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("PessoasInfo.Models.Detalhe", b =>
                {
                    b.HasOne("PessoasInfo.Models.Pessoa", null)
                        .WithMany("Detalhes")
                        .HasForeignKey("PessoaIdPessoa");
                });

            modelBuilder.Entity("PessoasInfo.Models.Telefone", b =>
                {
                    b.HasOne("PessoasInfo.Models.Pessoa", null)
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaIdPessoa");
                });

            modelBuilder.Entity("PessoasInfo.Models.Pessoa", b =>
                {
                    b.Navigation("Detalhes");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
